version: '2.4'
services:
  face:
    image: animcogn/face_recognition:cpu-latest
    container_name: face_recognition
    network_mode: host
    tty: true 
    ports:
      - 8000:8000
    privileged: true 
    volumes:
      - ../:/app
    command: ["bash"]